### ISSUE TITLE
Error with Jenkins Jobs Builder v1.6.1

### ISSUE THREAD

**Issue by anperez78** [rusty-dev/jenkins-job-builder-pipeline#3]
INFO:root:Updating jobs in ['./jobs'] ([])
Traceback (most recent call last):
  File "/usr/bin/jenkins-jobs", line 9, in <module>
    load_entry_point('jenkins-job-builder==1.6.1', 'console_scripts', 'jenkins-jobs')()
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 191, in main
    execute(options, config)
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 372, in execute
    n_workers=options.n_workers)
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 350, in update_jobs
    self.parser.generateXML()
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/parser.py", line 342, in generateXML
    self.xml_jobs.append(self.getXMLForJob(job))
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/parser.py", line 352, in getXMLForJob
    self.gen_xml(xml, data)
  File "/usr/lib/python2.7/site-packages/jenkins_jobs/parser.py", line 359, in gen_xml
    module.gen_xml(self, xml, data)
TypeError: gen_xml() takes exactly 3 arguments (4 given)

**Comment by rusty-dev** [comment]
Please use [stable](https://github.com/rusty-dev/jenkins-job-builder-pipeline/tree/stable) tag, current master branch contains the code for future\development versions of jenkins-job-builder.

**Comment by anperez78** [comment]
Yep, working perfectly now. Thanks.
